### ISSUE TITLE
Make table of contents in Juju docs same length as page length

### ISSUE THREAD

**Issue by tmihoc** [canonical/juju.is#362]
https://juju.is/docs/olm
https://juju.is/docs/sdk

The table of contents has a fixed length. For short pages that makes sense. However, for long pages it does not. There we could take advantage of the length of the page to expose more of the table of contents. I think that would improve document discoverability.

**Comment by anthonydillon** [comment]
@tmihoc do you mean that side navigation should reveal more items on long pages?

**Comment by tmihoc** [comment]
With the new plans to have expandable navigation, this might be a moot point. I'd close this issue.

**Comment by anthonydillon** [comment]
Great thanks

**Comment by Lukewh** [comment]
Expandable navigation has been implemented so this, I believe, is resolved :rocket:
