### ISSUE TITLE
Side navigation issues

### ISSUE THREAD

**Issue by bartaz** [canonical/juju.is#363]
As initially reported in Vanilla canonical-web-and-design/vanilla-framework#4121 it seems there are some problems with juju.is/docs side navigation.

Local overrides suggest that the side navigation was meant to be sticky:
https://github.com/canonical-web-and-design/juju.is/blob/7af548bbeff3426e7a38f155efbd2087c1c97fa2/static/sass/styles.scss#L233-L237

But for that it needs `is-sticky` class (on `.p-side-navigation` element).

If side nav is not meant to be sticky, local overrides should be removed as they cause bugs (#362)

**Comment by Lukewh** [comment]
With the collapsable side-navigation, this is no longer an issue.
