### ISSUE TITLE
Details block indentation

### ISSUE THREAD

**Issue by tmihoc** [canonical/juju.is#392]
I'd like the second [details]...[/details] block to appear indented under CLI tool Juju commands. Is there any way to do that?

Also, is there any way to put just a sublist in details, without being forced to attach a main list item to it? There's no real need for that "All `juju` commands" entry there---I used it merely to obtain nested indentation for the items that follow.

![image](https://user-images.githubusercontent.com/38667005/163383709-0a9827f1-c3ad-45be-b08a-c1c34b60d26b.png)

**Comment by Lukewh** [comment]
Do you have a link to where this is happening @tmihoc - does it still need looking at?

**Comment by tmihoc** [comment]
@Lukewh 

I don't have an example -- because it wasn't working well, I dropped it. But: I can easily reconstruct it (and partially have already). But: I don't think you need to worry about it anymore -- having thought about it some more, I think what I was looking for is probably both hard to achieve and a bad idea. I think we can close this now.
