### ISSUE TITLE
Juju website: odd title preview on LinkedIn or Slack

### ISSUE THREAD

**Issue by tmihoc** [canonical/juju.is#422]
![image](https://user-images.githubusercontent.com/38667005/176888866-27fed5e7-51c8-45f6-9e89-4b5702f134a1.png)

**Comment by Lukewh** [comment]
I think the solution here is to add the open graph meta tags to the head of the document. We'll take a look next iteration... Pulse.... Sprint.

**Comment by kevmgb** [comment]
@Lukewh I'd like to give this issue a try. Should the preview title be the "Take control of ..." heading?

**Comment by Lukewh** [comment]
> @Lukewh I'd like to give this issue a try. Should the preview title be the "Take control of ..." heading? Please view this [commit](https://github.com/canonical/juju.is/compare/main...kevmgb:juju.is:fix-title-preview) and advise on title meta tag.

Hey! Looks good, please propose a PR to main :)

**Comment by kevmgb** [comment]
@Lukewh done.

**Comment by tmihoc** [comment]
@Lukewh @kevmgb @steverydz Just wanted to say that the result now is still odd. For example, on Mattermost a juju.is title is always previewed as "Take control of Kubernetes" (see below) whereas the whole point of Juju is that it helps you take control of everything -- Kubernetes as well as non-Kubernetes.

![image](https://user-images.githubusercontent.com/38667005/215473405-81f6af75-b044-47e8-adfe-2a79739f826a.png)

Maybe we should try to make it show just "Take control"? It would be a more accurate preview of what we're trying to deliver.

**Comment by steverydz** [comment]
@tmihoc I've just updated the title to "Take control". It's now live.

**Comment by tmihoc** [comment]
@Lukewh @kevmgb @steverydz This is much better but people have commented that it's still weird how we don't get a preview of the actual page title. For every page we share, we just get "Take control" but no clue about the page itself. Is there any way to fix that?

**Comment by steverydz** [comment]
@tmihoc I've made a demo here: https://juju-is-446.demos.haus/

I've added a new block `{% block meta_title %}` to the template so if that is specified in the page it will show that instead of "Take control". Does that fix it for you?

**Comment by tmihoc** [comment]
@steverydz I tried the demo link. I cannot click on any pages from it (I get 500 errors), so everything I say is based just on my testing of the link for juju.is . 

What I found now is that https://juju-is-446.demos.haus/ gives a link preview of "Operator lifecycle manager for K8s and traditional workloads". This is actually worse than "Take control" , because it only picks up on the OLM bit of Juju. 

Imo the main page link should have a preview such as "Juju | Take control" or similar, and any subsequent link should have a preview of the form "Juju | <Title of the page>". (I've thought of "Juju | OLM | <Title of the page>", but that could get complicated really easily, so maybe the simpler versions is better.)

The problem right now is basically that any link from juju.is has the same preview. E.g., I copied four links to a Jira card, two Discourse links and two juju.is links. Here's the result. There is no way to distinguish between the ones from juju.is -- they both just say "Take control".


![image](https://user-images.githubusercontent.com/38667005/216595231-59029a31-9d21-411d-b535-3e0fe97670e3.png)

**Comment by steverydz** [comment]
@tmihoc For this demo I just copied the page title, however the content can be whatever we want: https://github.com/canonical/juju.is/pull/446/files#diff-37a968442c22648ceb4a16069820cc5350b97e50f45f26c5442d7c036ad743d2R4

**Comment by tmihoc** [comment]
@steverydz sounds good then.

**Comment by steverydz** [comment]
@tmihoc I've put that change live so this should be an improvement

**Comment by tmihoc** [comment]
This is much better, thanks a lot, @steverydz ! (Now, if we could get a preview of the first couple of lines that, that would be awesome, but it's fine if that comes in a future iteration!)
