### ISSUE TITLE
chevrons should be deleted from the side nav

### ISSUE THREAD

**Issue by anasereijo** [canonical/juju.is#425]
I am not sure why the chevrons were added, but I suspect it was because someone wanted to make it more clear that those links will open another level of navigation. This is not part of our [Side navigation pattern](https://vanillaframework.io/docs/patterns/navigation#side-navigation) guidelines, therefore I suggest deleting the chevrons. @danielmutis not sure if you have more context about this?

<img width="1323" alt="Screenshot 2022-07-07 at 14 25 21" src="https://user-images.githubusercontent.com/36884067/177785778-ed484258-2d96-4d01-ad03-2f720a6485c4.png">

**Comment by Lukewh** [comment]
@tmihoc @anasereijo can you two discuss this? It seems like the chevrons are an editorial addition that go against the Vanilla guidelines?

**Comment by tmihoc** [comment]
Hi. I was planning to delete them once we have the chevrons directly from the theme (cf. ongoing work by @danielmutis , @bartaz ). Till then, removing them would cause people to potentially miss out important content (especially in the Reference section where many items don't expand but some do and crucially so).

**Comment by fitojb** [comment]
The navigation no longer has hardcoded greater-than signs, as the site has been upgraded to Vanilla Framework 3.7.0, which includes an expandable side navigation pattern. This issue can be closed.

**Comment by bartaz** [comment]
Good catch @fitojb. Indeed this is not an issue anymore.
