### ISSUE TITLE
Proposal to change the tag for displaying blog artciles on this site.

### ISSUE THREAD

**Issue by mcjaeger** [canonical/juju.is#432]
The articles shown on [juju.is/blog ](https://juju.is/blog) are wordpress articles with the tag "juju.is". 

In parallel, the new tagging system for blog article content covers the tag "juju".

Proposal is to unify these two tags to "juju" only and thus change the rule so that articles with tag "juju" are shown on the juju.is/blog. Right now these articles are tagged with both tags "juju", to comply with the tagging system for content and "juju.is" for display on the special blog.

**Comment by Lukewh** [comment]
This proposal seems sane, we'll add this issue to our next pulse to update our blog filtering on juju.is :).

**Comment by steverydz** [comment]
Closing as fixed by this PR https://github.com/canonical/juju.is/pull/439
