### ISSUE TITLE
Change teaser blog entry from old 2021 to actual respondents gathering

### ISSUE THREAD

**Issue by mcjaeger** [canonical/juju.is#454]
Please change the teaser on https://juju.is/blog from the "read the 2021 report ..." to a teaser pointing to

https://ubuntu.com/engage/kubernetes-operations-survey

which contains the "win a RaspiCluster" campaign. In case a teaser graphics for that is required, maybe the RaspiCluster Image could be considered.

**Comment by mcjaeger** [comment]
@anthonydillon @Lukewh please let me know if that is actually the wrong place to ask for these kind of changed.

**Comment by Lukewh** [comment]
@mcjaeger apologies I've been OOO. We do not manage the editorial content, it's all done through WordPress. I believe you can update the featured blog-post through the WordPress admin interface. If you find the currently featured post, there should be somewhere that indicates that it's “featured”. Repeat the process in reverse for the post you want to be featured.
This is from a distant memory as, again, we don't manage the blog content :).
