### ISSUE TITLE
Copydoc extension points to the wrong document

### ISSUE THREAD

**Issue by mcjaeger** [canonical/juju.is#457]
For the page:

  https://juju.is/operator-day

a link is displayed in the copydoc extension pointing to a Google doc

  https://docs.google.com/document/d/1ZFRGkZ4vvvMVOgq4MIsBuebHsA7Y0rTyiZ76qjQpOAg/edit#

in fact the doc title is right, but the contents is not, please consider updating the copydoc.

**Comment by mcjaeger** [comment]
Hi @Lukewh, the document has changed, it shows also a copydoc for operator day, but it is the old one and reflecting the copydoc of this year's relaunch:
 
![Screenshot 2023-03-30 at 11 37 46](https://user-images.githubusercontent.com/3418977/228795366-6c7afbfb-9e4b-44b5-9303-32d7cc96b8d8.png)

**Comment by Lukewh** [comment]
Hi @mcjaeger, can you copy and paste the content from the new copy doc into the one linked from the website? The one linked from the website is the official directory for juju.is copy docs, thanks.

**Comment by mcjaeger** [comment]
hello @Lukewh understood.

I would prefer to have the issue kept open until the issue on juju.is. I think it would be more clear because until I did not copy the contents over as you have suggested, the issue is not fixed for juju.is.

I have copied this now.
