### ISSUE TITLE
Change https://juju.is/docs/olm  to  https://juju.is/docs/juju

### ISSUE THREAD

**Issue by tmihoc** [canonical/juju.is#477]
Please change https://juju.is/docs/olm  to  https://juju.is/docs/juju 

This it to align the Juju website with the new terminology (where the Juju OLM is just "Juju" and the Juju SDK is the "Charm SDK" or just the "SDK"). As the new terminology has already taken effect, it would be good if this change could be made as soon as possible. 

Requesting this on behalf @massigori , the PM for Juju.

Many thanks!

**Comment by tmihoc** [comment]
Hi @Lukewh , huge issue: All the links previously based on "olm" are now broken. We need to set up a redirect from anything based on "juju.is/docs/olm" to "juju.is/docs/juju". It's urgent, as otherwise all the formerly-OLM pages (that is, all the OLM-now-Juju docs) are broken.

Pinging @massigori to keep him in the loop.

Thanks to @nvinuesa for noticing the issue.

**Comment by Lukewh** [comment]
@tmihoc this is sorted now – thanks for reporting!

**Comment by tmihoc** [comment]
Thanks a lot, @Lukewh !
