### ISSUE TITLE
Add contact us form and "Get started with Juju" section

### ISSUE THREAD

**Issue by massigori** [canonical/juju.is#489]
The Juju website does not currently include the following component

- Contact us link pointing to form id 5332
- Getting started with Juju section

Copydoc [link ](https://docs.google.com/document/d/1IFnKQ3GQth7HSo1VlDy4nRyoFYPL9fjJN8jNuY8Nr2Q/edit?usp=sharing)- required changes highlighted in yellow

**Comment by steverydz** [comment]
@massigori This is live now
